# used for generate prometheusrule and alertmanagerconfig
- name: MysqlDown
  namespace: __namespace__
  expr: mysql_up{service="__fullname__",namespace="__namespace__"}
  message: MySQL instance {{ $labels.instance }} down
  for: 0m
  alertLevels:
    - compareOp: "=="
      compareValue: "0"
      severity: critical
  receivers:
    - name: gemcloud-default-webhook
      interval: 10m
- name: MysqlTooManyConnections
  namespace: __namespace__
  expr: max_over_time(mysql_global_status_threads_connected{service="__fullname__",namespace="__namespace__"}[1m]) / mysql_global_variables_max_connections{service="__fullname__",namespace="__namespace__"} * 100
  message: MySQL instance {{ $labels.instance }} too many connections > 80%
  for: 2m
  alertLevels:
    - compareOp: ">"
      compareValue: "80"
      severity: error
  receivers:
    - name: gemcloud-default-webhook
      interval: 10m
- name: MysqlSlowQueries
  namespace: __namespace__
  expr: increase(mysql_global_status_slow_queries{service="__fullname__",namespace="__namespace__"}[1m])
  message: MySQL instance {{ $labels.instance }} slow queries
  for: 2m
  alertLevels:
    - compareOp: ">"
      compareValue: "0"
      severity: error
  receivers:
    - name: gemcloud-default-webhook
      interval: 10m
- name: MysqlRestarted
  namespace: __namespace__
  expr: mysql_global_status_uptime{service="__fullname__",namespace="__namespace__"}
  message: MySQL instance {{ $labels.instance }} restarted
  for: 0m
  alertLevels:
    - compareOp: "<"
      compareValue: "60"
      severity: error
  receivers:
    - name: gemcloud-default-webhook
      interval: 10m
