apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: kubegems-appstore-charts
  name: kubegems-appstore-charts
  namespace: gemcloud-system
spec:
  backoffLimit: 3
  parallelism: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubegems-appstore-charts
      name: kubegems-appstore-charts
    spec:
      containers:
      - args:
        - --wait
        - --repo
        - kubegems
        - --server
        - http://kubegems-chartmuseum:8080
        image: kubegems/appstore-charts:latest
        imagePullPolicy: Always
        name: kubegems-appstore-charts
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
