# used for generate prometheusrule and alertmanagerconfig
- name: ConsulDown
  namespace: __namespace__
  expr: consul_up{service="__fullname__",namespace="__namespace__"}
  message: Consul [namespace {{ $labels.namespace }}] [service {{ $labels.service }}] [instance {{ $labels.instance }}] down
  for: 0m
  alertLevels:
    - compareOp: "=="
      compareValue: "0"
      severity: critical
  receivers:
    - name: gemcloud-default-webhook
      interval: 10m
- name: ConsulServiceHealthcheckFailed
  namespace: __namespace__
  expr: consul_catalog_service_node_healthy{service="__fullname__",namespace="__namespace__"}
  message: Consul service healthcheck failed [namespace {{ $labels.namespace }}] [service {{ $labels.service }}] [instance {{ $labels.instance }}]
  for: 0m
  alertLevels:
    - compareOp: "=="
      compareValue: "0"
      severity: critical
  receivers:
    - name: gemcloud-default-webhook
      interval: 10m