{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kafka.fullname" . }}-configuration
  namespace: {{ .Release.Namespace }}
  labels: {{- include "kafka.labels" . | nindent 4 }}
data:
  server.properties: |-
{{ .Values.config | indent 4 }}
{{- end -}}
