{{- if .Values.alerts.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheusrule.kubegems.io/name: {{ template "prometheus-rabbitmq-exporter.fullname" . }}
    prometheusrule.kubegems.io/type: monitor
  name: {{ template "prometheus-rabbitmq-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  groups:
  - name: RabbitmqNodeDown
    rules:
    - alert: RabbitmqNodeDown
      annotations:
        message: Rabbitmq [namespace {{"{{"}} $labels.namespace }}] [service {{"{{"}} $labels.service
          }}] [instance {{"{{"}} $labels.instance }}] node {{"{{"}} $labels.node }} down
        value: '{{"{{"}} $value | printf "%.1f" }}'
      expr: rabbitmq_running{service="{{ template "prometheus-rabbitmq-exporter.fullname" . }}",namespace="{{ .Release.Namespace }}"}==0
      for: 5m
      labels:
        gems_alert_from: monitor
        gems_alert_scope: normal
        gems_alertname: RabbitmqNodeDown
        gems_namespace: {{ .Release.Namespace }}
        severity: error
  - name: RabbitmqClusterDown
    rules:
    - alert: RabbitmqClusterDown
      annotations:
        message: The Rabbitmq cluster [namespace {{"{{"}} $labels.namespace }}] [service
          {{"{{"}} $labels.service }}] [instance {{"{{"}} $labels.instance }}] is maybe down.
        value: '{{"{{"}} $value | printf "%.1f" }}'
      expr: rabbitmq_up{service="{{ template "prometheus-rabbitmq-exporter.fullname" . }}",namespace="{{ .Release.Namespace }}"}==0
      for: 0m
      labels:
        gems_alert_from: monitor
        gems_alert_scope: normal
        gems_alertname: RabbitmqClusterDown
        gems_namespace: {{ .Release.Namespace }}
        severity: critical
  - name: RabbitMQClusterPartition
    rules:
    - alert: RabbitMQClusterPartition
      annotations:
        message: Rabbitmq cluster partition in Rabbitmq cluster was detected [namespace
          {{"{{"}} $labels.namespace }}] [service {{"{{"}} $labels.service }}] [instance {{"{{"}} $labels.instance
          }}] [node {{"{{"}} $labels.node }}]
        value: '{{"{{"}} $value | printf "%.1f" }}'
      expr: rabbitmq_partitions{service="{{ template "prometheus-rabbitmq-exporter.fullname" . }}",namespace="{{ .Release.Namespace }}"}>0
      for: 5m
      labels:
        gems_alert_from: monitor
        gems_alert_scope: normal
        gems_alertname: RabbitMQClusterPartition
        gems_namespace: {{ .Release.Namespace }}
        severity: critical
  - name: RabbitmqOutOfMemory
    rules:
    - alert: RabbitmqOutOfMemory
      annotations:
        message: The Rabbitmq [namespace {{"{{"}} $labels.namespace }}] [service {{"{{"}} $labels.service
          }}] [instance {{"{{"}} $labels.instance }}] [node {{"{{"}} $labels.node }}] is Out of
          memory
        value: '{{"{{"}} $value | printf "%.1f" }}'
      expr: rabbitmq_node_mem_used{service="{{ template "prometheus-rabbitmq-exporter.fullname" . }}",namespace="{{ .Release.Namespace }}"}
        / rabbitmq_node_mem_limit{service="{{ template "prometheus-rabbitmq-exporter.fullname" . }}",namespace="{{ .Release.Namespace }}"}
        * 100>90
      for: 5m
      labels:
        gems_alert_from: monitor
        gems_alert_scope: normal
        gems_alertname: RabbitmqOutOfMemory
        gems_namespace: {{ .Release.Namespace }}
        severity: error
  - name: RabbitmqTooManyConnections
    rules:
    - alert: RabbitmqTooManyConnections
      annotations:
        message: Too many connections to the Rabbitmq cluster [namespace {{"{{"}} $labels.namespace
          }}] [service {{"{{"}} $labels.service }}] [instance {{"{{"}} $labels.instance }}]
        value: '{{"{{"}} $value | printf "%.1f" }}'
      expr: rabbitmq_connectionsTotal{service="{{ template "prometheus-rabbitmq-exporter.fullname" . }}",namespace="{{ .Release.Namespace }}"}>1000
      for: 5m
      labels:
        gems_alert_from: monitor
        gems_alert_scope: normal
        gems_alertname: RabbitmqTooManyConnections
        gems_namespace: {{ .Release.Namespace }}
        severity: error
{{- end }}