# used for generate prometheusrule and alertmanagerconfig
- name: PostgresqlDown
  namespace: __namespace__
  expr: pg_up{service="__fullname__",namespace="__namespace__"}
  message: Postgresql [namespace {{ $labels.namespace }}] [service {{ $labels.service }}] [instance {{ $labels.instance }}] node {{ $labels.node }} down
  for: 0m
  alertLevels:
    - compareOp: "=="
      compareValue: "0"
      severity: critical
  receivers:
    - alertChannel:
        id: 1
      interval: 10m
- name: PostgresqlRestarted
  namespace: __namespace__
  expr: time() - pg_postmaster_start_time_seconds{service="__fullname__",namespace="__namespace__"}
  message: Postgresql restarted [namespace {{ $labels.namespace }}] [service {{ $labels.service }}] [instance {{ $labels.instance }}].
  for: 0m
  alertLevels:
    - compareOp: "<"
      compareValue: "60"
      severity: critical
  receivers:
    - alertChannel:
        id: 1
      interval: 10m
- name: PostgresqlTooManyConnections
  namespace: __namespace__
  expr: sum by (datname) (pg_stat_activity_count{datname!~"template.*|postgres",service="__fullname__",namespace="__namespace__"})
  message: Postgresql too many connections [namespace {{ $labels.namespace }}] [service {{ $labels.service }}] [instance {{ $labels.instance }}] [node {{ $labels.node }}],now {{ $value }}
  for: 2m
  alertLevels:
    - compareOp: ">"
      compareValue: 'pg_settings_max_connections{service="__fullname__",namespace="__namespace__"} * 0.8'
      severity: error
  receivers:
    - alertChannel:
        id: 1
      interval: 10m
