{{- if .Values.alerts.enabled -}}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  creationTimestamp: null
  labels:
    {{- include "prometheus-redis-exporter.labels" . | nindent 4 }}
    alertmanagerconfig.kubegems.io/name: {{ template "prometheus-redis-exporter.fullname" . }}
    alertmanagerconfig.kubegems.io/type: monitor
  name: {{ template "prometheus-redis-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  receivers:
  - name: "null"
  - name: gemcloud-default-webhook
    webhookConfigs:
    - httpConfig:
        tlsConfig:
          ca: {}
          cert: {}
          insecureSkipVerify: true
      url: https://kubegems-local-agent.kubegems-local:8041/alert
  route:
    groupBy:
    - gems_namespace
    - gems_alertname
    groupInterval: 30s
    groupWait: 30s
    receiver: "null"
    routes:
    - continue: true
      matchers:
      - name: gems_namespace
        value: {{ .Release.Namespace }}
      - name: gems_alertname
        value: RedisDown
      receiver: gemcloud-default-webhook
      repeatInterval: 10m
    - continue: true
      matchers:
      - name: gems_namespace
        value: {{ .Release.Namespace }}
      - name: gems_alertname
        value: RedisMemoryHigh
      receiver: gemcloud-default-webhook
      repeatInterval: 10m
    - continue: true
      matchers:
      - name: gems_namespace
        value: {{ .Release.Namespace }}
      - name: gems_alertname
        value: RedisTooManyConnections
      receiver: gemcloud-default-webhook
      repeatInterval: 10m
    - continue: true
      matchers:
      - name: gems_namespace
        value: {{ .Release.Namespace }}
      - name: gems_alertname
        value: RedisRejectedConnections
      receiver: gemcloud-default-webhook
      repeatInterval: 10m
{{- end }}