apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-cassandra-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-cassandra-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics 
      protocol: TCP
      name: metrics
  selector:
    {{- include "prometheus-cassandra-exporter.selectorLabels" . | nindent 4 }}
