{{- if .Values.alerts.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheusrule.kubegems.io/name: {{ template "prometheus-consul-exporter.fullname" . }}
    prometheusrule.kubegems.io/type: monitor
  name: {{ template "prometheus-consul-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  groups:
  - name: ConsulDown
    rules:
    - alert: ConsulDown
      annotations:
        message: Consul [namespace {{"{{"}} $labels.namespace }}] [service {{"{{"}} $labels.service
          }}] [instance {{"{{"}} $labels.instance }}] down
        value: '{{"{{"}} $value | printf "%.1f" }}'
      expr: consul_up{service="{{ template "prometheus-consul-exporter.fullname" . }}",namespace="{{ .Release.Namespace }}"}==0
      for: 0m
      labels:
        gems_alert_from: monitor
        gems_alert_scope: normal
        gems_alertname: ConsulDown
        gems_namespace: {{ .Release.Namespace }}
        severity: critical
  - name: ConsulServiceHealthcheckFailed
    rules:
    - alert: ConsulServiceHealthcheckFailed
      annotations:
        message: Consul service healthcheck failed [namespace {{"{{"}} $labels.namespace
          }}] [service {{"{{"}} $labels.service }}] [instance {{"{{"}} $labels.instance }}]
        value: '{{"{{"}} $value | printf "%.1f" }}'
      expr: consul_catalog_service_node_healthy{service="{{ template "prometheus-consul-exporter.fullname" . }}",namespace="{{ .Release.Namespace }}"}==0
      for: 0m
      labels:
        gems_alert_from: monitor
        gems_alert_scope: normal
        gems_alertname: ConsulServiceHealthcheckFailed
        gems_namespace: {{ .Release.Namespace }}
        severity: critical
{{- end }}