{{- if .Values.alerts.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheusrule.kubegems.io/name: {{ template "prometheus-memcached-exporter.fullname" . }}
    prometheusrule.kubegems.io/type: monitor
  name: {{ template "prometheus-memcached-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  groups:
  - name: MemcachedDown
    rules:
    - alert: MemcachedDown
      annotations:
        message: Memcached instance {{"{{"}} $labels.instance }} down
        value: '{{"{{"}} $value | printf "%.1f" }}'
      expr: memcached_up{service="{{ template "prometheus-memcached-exporter.fullname" . }}",namespace="{{ .Release.Namespace }}"}==0
      for: 0m
      labels:
        gems_alert_from: monitor
        gems_alert_scope: normal
        gems_alertname: MemcachedDown
        gems_namespace: {{ .Release.Namespace }}
        severity: critical
  - name: MemcachedLowAvalibleConnections
    rules:
    - alert: MemcachedLowAvalibleConnections
      annotations:
        message: memcached few available connections instance {{"{{"}} $labels.instance
          }}
        value: '{{"{{"}} $value | printf "%.1f" }}'
      expr: memcached_current_connections{service="{{ template "prometheus-memcached-exporter.fullname" . }}",namespace="{{ .Release.Namespace }}"}
        / memcached_max_connections{service="{{ template "prometheus-memcached-exporter.fullname" . }}",namespace="{{ .Release.Namespace }}"}
        * 100>90
      for: 0m
      labels:
        gems_alert_from: monitor
        gems_alert_scope: normal
        gems_alertname: MemcachedLowAvalibleConnections
        gems_namespace: {{ .Release.Namespace }}
        severity: error
{{- end }}