{{- if .Values.rbacEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "rabbitmq.fullname" . }}
  labels:
    app: {{ template "rabbitmq.name" . }}
    helm.sh/chart: {{ template "rabbitmq.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
