{{- if .Values.podSecurityPolicies.enabled -}}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: Role
metadata:
  name: {{ template "prometheus-elasticsearch-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ template "prometheus-elasticsearch-exporter.chart" . }}
    app: {{ template "prometheus-elasticsearch-exporter.name" . }}
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "prometheus-elasticsearch-exporter.fullname" . }}
{{- end }}
