{{- if .Values.alerts.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheusrule.kubegems.io/name: {{ template "prometheus-kafka-exporter.fullname" . }}
    prometheusrule.kubegems.io/type: monitor
  name: {{ template "prometheus-kafka-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec: {}
{{- end }}